Release 1.9.13-1 to unstable

diff --git a/debian/libapache2-mod.postinst.in b/debian/libapache2-mod.postinst.in
--- a/debian/libapache2-mod.postinst.in
+++ b/debian/libapache2-mod.postinst.in
@@ -5,48 +5,23 @@
 
 set -e
 
-apache_force_reload() {
-  if apache2ctl configtest 2>/dev/null; then
-    invoke-rc.d apache2 force-reload || true
-  else
-    echo "Your apache2 configuration is broken, please fix it and restart apache2 manually."
-  fi
-}
-
 # summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-#          <new-version>
-#        * <postinst> `abort-remove'
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
 #          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-case "$1" in
-    configure)
-      if [ -z "$2" ]; then # installing package
-        if [ -e /etc/apache2/apache2.conf ]; then
-          a2enmod @@module_name@@ >/dev/null || true
-          apache_force_reload
-        fi
-      else # upgrading package
-        if [ -e /etc/apache2/mods-enabled/@@module_name@@.load ]; then
-          apache_force_reload
-        fi
-      fi
-    ;;
-
-    abort-upgrade|abort-remove|abort-deconfigure)
-    ;;
-
-    *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
-esac
+if [ "$1" = "configure" ] ; then
+    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
+        . /usr/share/apache2/apache2-maintscript-helper
+        apache2_invoke enmod @@module_name@@  || exit 1
+    fi
+fi
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
